# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openslides.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keypad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypad_id', models.IntegerField(unique=True)),
                ('battery_level', models.SmallIntegerField(default=-1)),
                ('in_range', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('can_manage_votecollector', 'Can manage VoteCollector'),),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MotionPollKeypadConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, null=True)),
                ('keypad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openslides_votecollector.Keypad')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypad_data_list', to='motions.MotionPoll')),
            ],
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('seating_plan_x_axis', models.PositiveIntegerField()),
                ('seating_plan_y_axis', models.PositiveIntegerField()),
            ],
            options={
                'default_permissions': (),
                'ordering': ('pk',),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('seating_plan_x_axis', 'seating_plan_y_axis')]),
        ),
        migrations.AddField(
            model_name='keypad',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openslides_votecollector.Seat'),
        ),
        migrations.AddField(
            model_name='keypad',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
