# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import openslides.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_votecollector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status', models.CharField(default='No device', max_length=200)),
                ('voting_mode', models.CharField(max_length=50, null=True)),
                ('voting_target', models.IntegerField(default=0)),
                ('voting_duration', models.IntegerField(default=0)),
                ('voters_count', models.IntegerField(default=0)),
                ('votes_received', models.IntegerField(default=0)),
                ('is_voting', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
                'permissions': (('can_manage_votecollector', 'Can manage VoteCollector'),),
            },
            bases=(openslides.utils.models.RESTModelMixin, models.Model),
        ),
    ]
