# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_votecollector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keypad',
            options={'default_permissions': (), 'permissions': (('can_manage_votecollector', 'Can manage VoteCollector'),)},
        ),
        migrations.AlterModelOptions(
            name='motionpollkeypadconnection',
            options={'default_permissions': ()},
        ),
    ]
