# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_votecollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpollkeypadconnection',
            name='keypad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openslides_votecollector.Keypad'),
        ),
    ]
