# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openslides_votecollector', '0002_votecollector'),
        ('openslides_votecollector', '0002_auto_20160820_1655'),
    ]

    operations = [
    ]
